import { useEffect, useMemo, useState } from 'react';
import { Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom';
import { devices, getDeviceById } from './data/devices';
import { formatDate, getRomById, roms } from './data/roms';

const types = ['Stock ROM', 'Custom ROM', 'Firmware', 'Recovery', 'Kernel', 'GApps', 'Other'];
const androidVersions = ['Android 14', 'Android 13', 'Android 12', 'Android 11'];
const allText = (r) => [r.name, r.device, r.codename, r.androidVersion, r.type, r.version, r.maintainer].join(' ').toLowerCase();

function App() {
  const [theme, setTheme] = useState(() => localStorage.getItem('rom-vault-theme') || (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'));
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('rom-vault-theme', theme); }, [theme]);
  return <div className="app-shell"><Header theme={theme} toggle={() => setTheme(theme === 'dark' ? 'light' : 'dark')} /><main><Routes><Route path="/" element={<Home />} /><Route path="/devices/:id" element={<Device />} /><Route path="/:id" element={<Device />} /><Route path="/roms" element={<Catalog />} /><Route path="/roms/:romId" element={<Detail />} /><Route path="/download/:romId" element={<Detail />} /><Route path="/guides" element={<Info title="Device guides" text="Learn the fundamentals of bootloader unlocking, recovery flashing, and checksum verification before you begin." />} /><Route path="/about" element={<Info title="About ROM Vault" text="A focused, sample-safe discovery experience for Redmi and POCO Android enthusiasts. Real developer-hosted sources can be connected later." />} /><Route path="*" element={<NotFound />} /></Routes></main><Footer /></div>;
}
function Header({ theme, toggle }) { const [open, setOpen] = useState(false); return <header className="topbar glass"><Link to="/" className="logo" onClick={() => setOpen(false)}><b>RV</b><span>ROM Vault<small>ANDROID ARCHIVE</small></span></Link><button className="menu-button" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>☰</button><nav className={open ? 'open' : ''}>{[['Home','/'],['Devices','/devices/redmi-note-11t-5g'],['ROMs','/roms'],['Guides','/guides'],['About','/about']].map(([label,to]) => <NavLink key={to} to={to} end={to === '/'} onClick={() => setOpen(false)}>{label}</NavLink>)}</nav><button className="theme" onClick={toggle} aria-label="Toggle theme">{theme === 'dark' ? '☼' : '☾'}</button></header>; }
function Home() { const [query, setQuery] = useState(''); const matches = devices.filter(d => `${d.name} ${d.codename}`.toLowerCase().includes(query.toLowerCase())); return <><section className="hero"><div><span className="eyebrow">CURATED ANDROID ARCHIVE · 01</span><h1>Your Android<br /><em>starts here.</em></h1><p>Explore ROMs, firmware, recoveries and essential files for supported Redmi and POCO devices.</p><div className="hero-actions"><Link className="button primary" to="/devices/redmi-note-11t-5g">Browse devices <span>↗</span></Link><Link className="button secondary" to="/roms">Latest ROMs</Link></div></div><div className="hero-orb" aria-hidden="true"><div className="phone-mockup"><i /><strong>ROM<br />VAULT</strong><small>11T 5G</small></div></div></section><section className="search-section glass"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search devices by name or codename…" aria-label="Search devices" /><kbd>⌘ K</kbd></section><section className="section"><SectionTitle eyebrow="SUPPORTED HARDWARE" title="Choose your device" action="View ROM archive" to="/roms" /><div className="device-grid">{matches.map(d => <DeviceCard key={d.id} device={d} />)}</div>{!matches.length && <Empty title="No devices found" text="Try searching for Redmi, POCO, xaga, or miles." />}</section><section className="metrics glass"><div><b>2</b><span>Supported devices</span></div><div><b>{roms.length}</b><span>Sample releases</span></div><div><b>100%</b><span>Sample-labelled</span></div></section></>; }
function DeviceVisual({ device }) { return <div className={`device-visual ${device.accent}`} aria-label={`${device.name} placeholder device visual`}><div className="mock-phone"><span /><b>{device.codename.toUpperCase()}</b><small>DEVICE MOCKUP</small></div></div>; }
function DeviceCard({ device }) { return <Link to={`/devices/${device.id}`} className="device-card glass"><DeviceVisual device={device} /><div className="card-content"><span className="tag">{device.androidVersions[0]}</span><h3>{device.name}</h3><p>{device.summary}</p><div className="meta"><span>codename <b>{device.codename}</b></span><span><b>{device.romCount}</b> ROMs</span></div><span className="text-link">View ROMs <b>↗</b></span></div></Link>; }
function Device() { const { id } = useParams(); const device = getDeviceById(id); if (!device) return <NotFound />; return <><Breadcrumb items={['Home', device.name]} /><section className="device-hero glass"><DeviceVisual device={device} /><div><span className="eyebrow">DEVICE PROFILE · {device.manufacturer.toUpperCase()}</span><h1>{device.name}</h1><p>{device.summary}</p><div className="meta large"><span>Codename <b>{device.codename}</b></span><span>{device.romCount} catalogued ROMs</span><span>Firmware <b>{device.firmware}</b></span></div></div></section><div className="notice"><b>! &nbsp; Compatibility notice</b><span>Always verify your exact device variant and codename before flashing any ROM or firmware.</span></div><section className="device-info"><div className="glass info-box"><SectionTitle eyebrow="HARDWARE" title="At a glance" />{device.specs.map(s => <div className="spec" key={s.label}><span>{s.label}</span><b>{s.value}</b></div>)}</div><div className="glass info-box"><SectionTitle eyebrow="SUPPORT" title="Android availability" /><div className="chip-list">{device.androidVersions.map(v => <span className="tag" key={v}>{v}</span>)}</div><p>Browse sample metadata for this device in the catalog. Download sources remain disabled until legitimate sources are connected.</p><Link to="/roms" className="button secondary">Open full catalog</Link></div></section><section className="section"><SectionTitle eyebrow="DEVICE ARCHIVE" title="Available ROMs" /><Catalog deviceId={device.id} embedded /></section></>; }
function Catalog({ deviceId, embedded = false }) { const [q,setQ]=useState(''); const [type,setType]=useState('All'); const [android,setAndroid]=useState('All'); const [sort,setSort]=useState('newest'); const [loading,setLoading]=useState(!embedded); useEffect(() => { if (!embedded) { const t=setTimeout(()=>setLoading(false),350); return()=>clearTimeout(t); } },[embedded]); const filtered=useMemo(()=>roms.filter(r=>(!deviceId||r.deviceId===deviceId)&&(!q||allText(r).includes(q.toLowerCase()))&&(type==='All'||r.type===type)&&(android==='All'||r.androidVersion===android)).sort((a,b)=>sort==='oldest'?new Date(a.releaseDate)-new Date(b.releaseDate):sort==='android'?b.androidVersion.localeCompare(a.androidVersion):new Date(b.releaseDate)-new Date(a.releaseDate)),[q,type,android,sort,deviceId]); const reset=()=>{setQ('');setType('All');setAndroid('All');setSort('newest');}; return <div className={embedded?'catalog embedded':'catalog'}>{!embedded&&<><Breadcrumb items={['Home','ROM catalog']} /><SectionTitle eyebrow="THE ARCHIVE" title="Browse ROMs & firmware" /><p className="lead">Search the complete sample catalog by device, version, type, or maintainer.</p></>}<div className="filters glass"><div className="input-wrap">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search ROMs, devices, codenames…" aria-label="Search ROMs" /></div><select value={type} onChange={e=>setType(e.target.value)} aria-label="Filter by ROM type"><option>All</option>{types.map(t=><option key={t}>{t}</option>)}</select><select value={android} onChange={e=>setAndroid(e.target.value)} aria-label="Filter by Android version"><option>All</option>{androidVersions.map(v=><option key={v}>{v}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort ROMs"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="android">Android version</option></select><button className="reset" onClick={reset}>Reset</button></div><div className="result-line"><span>{loading?'Loading…':`${filtered.length} result${filtered.length!==1?'s':''}`}</span>{q&&<b> for “{q}”</b>}</div>{loading?<Skeleton />:filtered.length?<div className="rom-grid">{filtered.map(r=><RomCard key={r.id} rom={r}/>)}</div>:<Empty title="No ROMs found" text="Reset your search or filters to see the sample archive." action={reset}/>}</div>; }
function RomCard({rom}) { return <article className="rom-card glass"><div className="rom-top"><span className="tag">{rom.type}</span><span className="sample">SAMPLE DATA</span></div><h3>{rom.name}</h3><p>{rom.device} · <b>{rom.codename}</b></p><div className="rom-details"><span><small>ANDROID</small><b>{rom.androidVersion}</b></span><span><small>BUILD</small><b>{rom.version}</b></span><span><small>SIZE</small><b>{rom.size}</b></span><span><small>RELEASED</small><b>{formatDate(rom.releaseDate)}</b></span></div><div className="rom-bottom"><span>{rom.maintainer}</span><Link className="button secondary" to={`/roms/${rom.id}`}>View details</Link></div></article>; }
function Detail() { const {romId}=useParams(); const rom=getRomById(romId); const [copied,setCopied]=useState(false); if(!rom)return <NotFound/>; const copy=async()=>{try{await navigator.clipboard.writeText(rom.checksum);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{}}; return <><Breadcrumb items={['Home','ROM catalog',rom.name]}/><section className="detail-hero glass"><div><span className="sample">DEMO / SAMPLE DATA</span><h1>{rom.name}</h1><p>{rom.device} · {rom.codename}</p></div><button className="button disabled" disabled>Download unavailable</button></section><div className="notice warning"><b>! &nbsp; Flashing safety</b><span>Verify your exact device model and codename before flashing. Incorrect firmware or ROM files may cause boot failure or other device problems.</span></div><section className="detail-grid"><div className="glass info-box"><SectionTitle eyebrow="FILE INFORMATION" title="Release details" />{[['Android',rom.androidVersion],['Version',rom.version],['Build',rom.build],['Type',rom.type],['File size',rom.size],['Release date',formatDate(rom.releaseDate)],['Maintainer',rom.maintainer]].map(([a,b])=><div className="spec" key={a}><span>{a}</span><b>{b}</b></div>)}</div><div className="glass info-box"><SectionTitle eyebrow="VERIFICATION" title="Checksum" /><div className="checksum"><code>{rom.checksum}</code><button className="button secondary" onClick={copy}>{copied?'Copied ✓':'Copy SHA-256'}</button></div><p className="muted">This checksum is illustrative sample metadata and does not correspond to a downloadable file.</p><hr/><SectionTitle eyebrow="CHANGELOG" title="What’s included"/><p>{rom.changelog}</p><div className="source-note">Download source: <b>Not connected</b><br/>Mirror links: <b>None provided</b></div></div></section></>; }
function SectionTitle({eyebrow,title,action,to}) { return <div className="section-title"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{action&&<Link className="text-link" to={to}>{action} ↗</Link>}</div>; }
function Breadcrumb({items}) { return <nav className="breadcrumbs" aria-label="Breadcrumb">{items.map((i,n)=><span key={i}>{n? ' / ':''}{n===items.length-1?i:<Link to={n?'#':'/'}>{i}</Link>}</span>)}</nav>; }
function Empty({title,text,action}) { return <div className="empty glass"><div>⌁</div><h3>{title}</h3><p>{text}</p>{action&&<button className="button secondary" onClick={action}>Reset filters</button>}</div>; }
function Skeleton(){return <div className="rom-grid">{[1,2,3].map(i=><div className="skeleton glass" key={i}/>)}</div>;}
function Info({title,text}) { return <section className="content glass"><span className="eyebrow">ROM VAULT</span><h1>{title}</h1><p>{text}</p><Link className="button primary" to="/roms">Explore catalog</Link></section>; }
function NotFound(){return <section className="content glass not-found"><span className="eyebrow">ERROR 404</span><h1>Lost in the archive.</h1><p>That page doesn't exist or the requested sample was removed.</p><Link className="button primary" to="/">Back home</Link></section>;}
function Footer(){return <footer><span><b>RV</b> ROM Vault</span><small>Sample portal · verify every source before flashing.</small></footer>;}
export default App;
